import React, { useState, useEffect } from "react";

// import HeaderAnimationProtestMonoLetter from "./HeaderAnimationProtestMonoLetter";

const HeaderAnimationProtestMono = () => {
  const [index, setIndex] = useState(0);

  const array = [
    "Tomorrow",
    "HD Sneaker",
    "Stack of Faux Cash.",
    "Demna Gvasalia",
    "Joe Freshgoods",
    "Raw Architecture",
    "ProtestProtest",
    "GroteskGrotesk",
  ];

  useEffect(() => {
    const timer = setInterval(() => {
      setIndex(Math.floor(Math.random() * array.length));
    }, 500);
    return () => clearInterval(timer);
  }, []);
  return (
    <div>
      {/* <div className={"PGMonoAnimationWrapper"}> */}
      {/* <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />{" "}
      <HeaderAnimationProtestMonoLetter glyph={"m"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"i"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"b"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"h"} />
      <HeaderAnimationProtestMonoLetter glyph={"a"} />
      <HeaderAnimationProtestMonoLetter glyph={"n"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} />
      <HeaderAnimationProtestMonoLetter glyph={"s"} />
      <HeaderAnimationProtestMonoLetter glyph={"t"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"r"} />
      <HeaderAnimationProtestMonoLetter glyph={"e"} />
      <HeaderAnimationProtestMonoLetter glyph={"o"} />
      <HeaderAnimationProtestMonoLetter glyph={"/"} /> */}
      {/* </div> */}
      <div className={"headerAnimationWrapper"}>
        <div className={"headerAnimationSubWrapper"}>
          <div className={"row"}>
            <p>
              {array[index]}
              <br />
            </p>
          </div>
          <div className={"row2"}>
            <p>
              {array[index]}
              <br />
            </p>
          </div>
          <div className={"row"}>
            <p>
              {array[index]}
              <br />
            </p>
          </div>
          <div className={"row2"}>
            <p>
              {array[index]}
              <br />
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HeaderAnimationProtestMono;
