/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/happyface/230102_logo.gltf -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Logo = () => {
  const { nodes, materials } = useGLTF('/happyface/230102_logo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Shiny Plastic']} position={[-0.06, -0.43, -0.64]} />
      <mesh geometry={nodes.SADFACE001.geometry} material={materials.Material} position={[0.01, 0.28, -0.54]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

export default Logo

useGLTF.preload('/happyface/230102_logo.gltf')
